### ISSUE TITLE
Install deepdetect on CentOS

### ISSUE THREAD

**Issue by anguoyang** [jolibrain/deepdetect#71] opened 2016-02-24 13:33 UTC
Hi,
I tried to install dependencies on CentOS with similar scripts, however, it did not work:
 yum install build-essential libgoogle-glog-dev libgflags-dev libeigen3-dev libopencv-dev libcppnetlib-dev libboost-dev libcurlpp-dev libcurl4-openssl-dev protobuf-compiler libopenblas-dev libhdf5-dev libprotobuf-dev libleveldb-dev libsnappy-dev liblmdb-dev libutfcpp-dev
Loaded plugins: security
Setting up Install Process
No package build-essential available.
No package libgoogle-glog-dev available.
No package libgflags-dev available.
No package libeigen3-dev available.
No package libopencv-dev available.
No package libcppnetlib-dev available.
No package libboost-dev available.
No package libcurlpp-dev available.
No package libcurl4-openssl-dev available.
No package libopenblas-dev available.
No package libhdf5-dev available.
No package libprotobuf-dev available.

Does it mean, that I have to compiled all those source code one by one for installation?

**Comment by beniz** [comment] 2016-02-24 13:54
hi @anguoyang, FYI CentOS is not yet supported by CentOS / RedHat is on our roadmap. In the meantime, you shouldn't have to recompile the libraries above. There certainly is a one-to-one match between Ubuntu and Redhat/CentOS packages. If you search them one by one with `yum`, and you should find each of the packages without too much trouble as they are pretty standard.

Typically see http://unix.stackexchange.com/questions/63358/what-would-be-the-rhel-package-corresponding-to-build-essential-in-ubuntu and similar links.

Let us know once you get the list and if you have further trouble.

**Comment by anguoyang** [comment] 2016-02-24 14:11
"CentOS is not yet supported by CentOS / RedHat is on our roadmap", does it mean that we could not build/install deepdetect on CentOS right now? OR, if I "search them one by one with yum and find each of the packages" then I could also compile/run deepdetect on CentOS?

**Comment by beniz** [comment] 2016-02-24 14:17
There was a typo in my answer, see the fixed sentence "but RedHat is on our roadmap".

So, yes it means that you certainly can build deepdetect on CentOS, and it shouldn't be too difficult. No support means we are cannot ensure at this stage that it will build out of the box without effort and that we are not providing fixes for that in the distributed code (yet).

**Comment by anguoyang** [comment] 2016-02-24 14:21
Ok, great! thanks a lot for your answer,

**Comment by anguoyang** [comment] 2016-02-24 15:07
It seems that build-essential could be replaced with "yum groupinstall "Development Tools", however, for other packages, I could not find proper "yum" replacements, maybe I have to compile it by source code.

**Comment by beniz** [comment] 2016-02-24 15:36
These packages are standard, they do exist under CentOS, you'll need to find them by hand, see http://unix.stackexchange.com/questions/75279/finding-yum-equivalents-of-apt-repositories

**Comment by anguoyang** [comment] 2016-02-25 06:38
Yes, I found some of them, but have to change the names, for example: libboost-dev to boost-devel, or libsnappy-dev to snappy-devel, however, there are still 3 packages:libcurl4-openssl-dev, libcppnetlib-dev and libutfcpp-dev, which I could not simply replace libxxx-dev into xxx-devel for installation.

**Comment by beniz** [comment] 2016-02-25 08:00
You're almost there then. 

Here is what I could find:
- `libcurl`: http://serverfault.com/questions/701447/yum-does-not-contain-the-package-libcurl
- `utfcpp` appears to be header-based, i.e. no compilation needed, find it here: https://sourceforge.net/projects/utfcpp/
- `cpp-netlib`: you need to compile it I'm afraid, but this is no big deal. Go get the last version here: http://cpp-netlib.org/
Also, you can look at https://github.com/beniz/deepdetect/issues/29#issue-114813291 that explains how to compile `cpp-netlib` on Ubuntu.

Let me know how it goes, and thanks for your perseverance.

**Comment by anguoyang** [comment] 2016-02-25 12:43
I found utfcpp finally, "yum install utfcpp8-devel" :)
For the netlib, I downloaded the source code, but as my CentOS version is 6.7, the GCC version is < 4.8, so it is not possible for me to compile it, I have to update the GCC by way of compiling the GCC source code, now it is OK now, and compiled the netlib successfully.
For the libcurl, yes, "curl-devel" could be found on  CentOS, however, I could not find libcurl4-openssl-dev.

**Comment by anguoyang** [comment] 2016-02-25 14:37
I have compiled deepdetect finally, however, when I run ./dede, it generated "segmentation error"

**Comment by anguoyang** [comment] 2016-02-25 14:47
My CentOS version:6.7, maybe it is more easier on CentOS 7

**Comment by anguoyang** [comment] 2016-02-25 15:03
Where can I find the logs? I want to solve the "segmentation error"

**Comment by beniz** [comment] 2016-02-25 15:04
I can't say for sure though it is likely. You can also try to run with gdb then get a back trace with the `bt` command from gdb.

**Comment by anguoyang** [comment] 2016-02-25 15:35
OK, I will try on it, BTW, is it possible to build a docker package? it will be very convenient for installation

**Comment by beniz** [comment] 2016-02-25 15:46
Yes this a point, please open an issue requesting it

**Comment by anguoyang** [comment] 2016-02-25 23:43
Ok, thanks.

**Comment by Isaacpm** [comment] 2016-03-06 11:34
Hi guys,
hit a roadblock with the CentOS 7 installation, and would like some advice, because it's getting out of control.
I'm getting this error:
```
/root/deepdetect/src/commandlineapi.cc: In member function ‘int dd::CommandLineAPI::boot(int, char**)’:
/root/deepdetect/src/commandlineapi.cc:46:5: error: ‘ParseCommandLineFlags’ is not a member of ‘google’
     google::ParseCommandLineFlags(&argc, &argv, true);
     ^
/root/deepdetect/src/commandlineapi.cc:46:5: note: suggested alternative:
In file included from /usr/include/glog/logging.h:85:0,
                 from /root/deepdetect/src/imginputfileconn.h:30,
                 from /root/deepdetect/src/services.h:29,
                 from /root/deepdetect/src/apistrategy.h:26,
                 from /root/deepdetect/src/commandlineapi.h:25,
                 from /root/deepdetect/src/commandlineapi.cc:22:
/usr/include/gflags/gflags.h:346:31: note:   ‘gflags::ParseCommandLineFlags’
 extern GFLAGS_DLL_DECL uint32 ParseCommandLineFlags(int *argc, char*** argv, bool remove_flags);
                               ^
make[2]: *** [src/CMakeFiles/ddetect.dir/commandlineapi.cc.o] Error 1
make[1]: *** [src/CMakeFiles/ddetect.dir/all] Error 2

```

All solutions I found point to compiling glflags with GFLAGS_NAMESPACE defined, like in:
https://github.com/BVLC/caffe/issues/890

The problem is that compiling gflags required a newer cmake version, and when I compile the new cmake version, things start getting very messy, because the other cmakes stop working.

Any suggestions, before I continue with the gflags compilation path?
As it seems really complicated for the installation.

Thanks,
Isaac

**Comment by beniz** [comment] 2016-03-06 11:49
OK, didn't know CentOS7 was this much behind. So a quick fix for you to move forward is to replace the `google::Parse` with `gflags::Parse` everywhere, i.e. in all `*api.cc` files. This should allow to link to the old `gflags` library, and should work fine.

I'd advise not go into recompiling `cmake` for now, as this would deepen the nightmare ;)

**Comment by Isaacpm** [comment] 2016-03-06 17:32
I didn't want to change the source code, I think it's custom enough as follows...., so the following steps will get it ready for a dede installation following the website instructions.
There are a couple of things I don't like much, and could probably be improved, but it's a good base, I'll mark it in the steps.
It ends with these warnings, I don't have time to check if it trains and predicts, but it starts:
```
/usr/bin/ld: warning: libgflags.so.2.1, needed by /usr/lib/gcc/x86_64-redhatlinux/4.8.5/../../../../lib64/libglog.so, may conflict with libgflags.so.2
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
```

The steps are:
```
yum groupinstall "Development Tools"
yum install -y wget 
wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
rpm -Uvh epel-release-7-5.noarch.rpm
yum upgrade -y


yum install -y opencv-devel.x86_64 protobuf-devel.x86_64 protobuf-compiler.x86_64 cmake git glog-devel.x86_64 openblas-devel.x86_64 eigen3-devel.noarch hdf5-devel.x86_64 leveldb-devel.x86_64 lmdb-devel.x86_64 snappy-devel.x86_64 libcurl-devel.x86_64 libcurl.x86_64 utf8cpp-devel.noarch openssl-devel.x86_64 yum-utils.noarch

wget https://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz
tar -xvzf boost_1_60_0.tar.gz
cd boost_1_60_0/
./bootstrap.sh --with-libraries=atomic,date_time,exception,filesystem,iostreams,locale,program_options,regex,signals,system,test,thread,timer,log
./b2 install

cd ..

git clone https://github.com/jpbarrette/curlpp
cd curlpp
./autogen.sh
./configure
make
make install

cd ..

wget http://downloads.cpp-netlib.org/0.11.2/cpp-netlib-0.11.2-final.tar.gz
tar -xvzf cpp-netlib-0.11.2-final.tar.gz 
cd cpp-netlib-0.11.2-final
mkdir cpp-netlib-build
cd cpp-netlib-build/
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ..
make
make install

cd ..
cd ..

#These three steps are not very clean, but couldn't get it to work in another way
cp -rva /usr/local/include/boost/* /usr/include/
cp /usr/include/openblas/* /usr/include/
cp -rva /root/cpp-netlib-0.11.2-final/boost/ /usr/include

wget https://github.com/gflags/gflags/archive/v2.0.zip
unzip v2.0.zip
cd gflags-2.0/
./configure
make
make install

cd ..

deepdetect installation following website instructions
```

**Comment by Isaacpm** [comment] 2016-03-06 18:05
I followed the training from text example and I'm getting this error when querying the status of the service:
```
ERROR - service n20 training status call failed
ERROR - {"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}
```

All previous commands are successful and job is created/assigned a number.
I wonder if it's because any of the two warnings

**Comment by beniz** [comment] 2016-03-06 19:44
Good job getting it to compile! The first thing would be to check that the unit tests are passing.

For this you may want to compile with 
```
cmake .. -DBUILD_TESTS=ON
make
cd tests/
./ut_jsonapi
./ut_caffeapi
...
```

**Comment by Isaacpm** [comment] 2016-03-06 20:56
Fixed one of the issues by compiling the right version of glog but the clock skew one is still there. And updated the previous comment with the instructions, in case you want to get to the compilated state.
Let's go test by test, first test to fail:

```
./ut_caffeapi 
Running main() from gtest_main.cc
[==========] Running 11 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 11 tests from caffeapi
[ RUN      ] caffeapi.service_train

ERROR - service my_service mllib bad param: missing solver file in ../examples/caffe/mnist/
joutstr={"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}
/root/deepdetect/tests/ut-caffeapi.cc:79: Failure
Value of: jd["status"]["code"].GetInt()
  Actual: 400
Expected: 201
[  FAILED  ] caffeapi.service_train (1 ms)
[ RUN      ] caffeapi.service_train_async_status_delete
joutstr={"status":{"code":201,"msg":"Created"},"head":{"method":"/train","job":1,"status":"running"}}

ERROR - service my_service training status call failed

ERROR - {"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}
status joutstr={"status":{"code":200,"msg":"OK"},"head":{"method":"/train","job":1,"status":"error"},"body":{}}
unknown file: Failure
C++ exception with description "false" thrown in the test body.
[  FAILED  ] caffeapi.service_train_async_status_delete (1 ms)
[ RUN      ] caffeapi.service_train_async_final_status
joutstr={"status":{"code":201,"msg":"Created"},"head":{"method":"/train","job":1,"status":"running"}}

ERROR - service my_service training status call failed

ERROR - {"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}
joutstr={"status":{"code":200,"msg":"OK"},"head":{"method":"/train","job":1,"status":"error"},"body":{}}
unknown file: Failure
C++ exception with description "false" thrown in the test body.
[  FAILED  ] caffeapi.service_train_async_final_status (0 ms)
[ RUN      ] caffeapi.service_train_async_and_predict
joutstr={"status":{"code":201,"msg":"Created"},"head":{"method":"/train","job":1,"status":"running"}}

ERROR - service my_service training status call failed

ERROR - {"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}
joutstr={"status":{"code":200,"msg":"OK"},"head":{"method":"/train","job":1,"status":"error"},"body":{}}

ERROR - service my_service mllib bad param: no deploy file in ../examples/caffe/mnist/ for initializing the net
joutstr={"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}
/root/deepdetect/tests/ut-caffeapi.cc:257: Failure
Value of: jd["status"]["code"]
  Actual: 24-byte object <90-01 00-00 00-00 00-00 00-00 00-00 00-00 00-00 06-3E 00-00 00-00 00-00>
Expected: 409
[  FAILED  ] caffeapi.service_train_async_and_predict (1 ms)
[ RUN      ] caffeapi.service_predict

ERROR - service my_service mllib bad param: missing solver file in ../examples/caffe/mnist/
joutstr={"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}
/root/deepdetect/tests/ut-caffeapi.cc:283: Failure
Value of: jd["status"]["code"].GetInt()
  Actual: 400
Expected: 201
[  FAILED  ] caffeapi.service_predict (0 ms)
[ RUN      ] caffeapi.service_train_csv
instantiating model template mlp

INFO - source=../templates/caffe/mlp/

INFO - dest=../examples/all/forest_type//mlp.prototxt

ERROR - service my_service mllib bad param: missing solver file in ../examples/all/forest_type/
joutstr={"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}
/root/deepdetect/tests/ut-caffeapi.cc:367: Failure
Value of: jd["status"]["code"].GetInt()
  Actual: 400
Expected: 201
[  FAILED  ] caffeapi.service_train_csv (3 ms)
[ RUN      ] caffeapi.service_train_csv_in_memory
instantiating model template mlp

INFO - source=../templates/caffe/mlp/

INFO - dest=../examples/all/forest_type//mlp.prototxt

ERROR - service my_service2 mllib bad param: missing solver file in ../examples/all/forest_type/
joutstr={"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}
/root/deepdetect/tests/ut-caffeapi.cc:470: Failure
Value of: jd["status"]["code"].GetInt()
  Actual: 400
Expected: 201
[  FAILED  ] caffeapi.service_train_csv_in_memory (19 ms)
[ RUN      ] caffeapi.service_train_images
instantiating model template cifar

INFO - source=../templates/caffe/cifar/

INFO - dest=plank/cifar.prototxt

ERROR - service my_service mllib bad param: missing solver file in plank
joutstr={"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}
/root/deepdetect/tests/ut-caffeapi.cc:524: Failure
Value of: jd["status"]["code"].GetInt()
  Actual: 400
Expected: 201
[  FAILED  ] caffeapi.service_train_images (2 ms)
[ RUN      ] caffeapi.service_train_txt
instantiating model template mlp

INFO - source=../templates/caffe/mlp/

INFO - dest=n20/mlp.prototxt

ERROR - service my_service mllib bad param: missing solver file in n20
joutstr={"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}
/root/deepdetect/tests/ut-caffeapi.cc:563: Failure
Value of: jd["status"]["code"].GetInt()
  Actual: 400
Expected: 201
[  FAILED  ] caffeapi.service_train_txt (2 ms)
[ RUN      ] caffeapi.service_train_txt_char
instantiating model template convnet

INFO - source=../templates/caffe/convnet/

INFO - dest=n20/convnet.prototxt

ERROR - service my_service mllib bad param: missing solver file in n20
joutstr={"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}
/root/deepdetect/tests/ut-caffeapi.cc:601: Failure
Value of: jd["status"]["code"].GetInt()
  Actual: 400
Expected: 201
[  FAILED  ] caffeapi.service_train_txt_char (2 ms)
[ RUN      ] caffeapi.service_train_csv_mt_regression
instantiating model template mlp

INFO - source=../templates/caffe/mlp/

INFO - dest=sflare/mlp.prototxt
jtrainstr={"service":"my_service","async":false,"parameters":{"input":{"test_split":0.1,"shuffle":true,"label":["c_class","m_class","x_class"],"separator":",","scale":true,"categoricals":["class_code","code_spot","code_spot_distr"]},"mllib":{"gpu":true,"solver":{"iterations":2000,"test_interval":200,"base_lr":0.001,"snapshot":2000,"test_initialization":true},"net":{"batch_size":100}},"output":{"measure":["eucll"]}},"data":["../examples/all/sflare/flare.csv"]}

ERROR - service my_service mllib bad param: missing solver file in sflare
joutstr={"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error"}}
/root/deepdetect/tests/ut-caffeapi.cc:640: Failure
Value of: jd["status"]["code"].GetInt()
  Actual: 400
Expected: 201
[  FAILED  ] caffeapi.service_train_csv_mt_regression (1 ms)
[----------] 11 tests from caffeapi (32 ms total)

[----------] Global test environment tear-down
[==========] 11 tests from 1 test case ran. (32 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 11 tests, listed below:
[  FAILED  ] caffeapi.service_train
[  FAILED  ] caffeapi.service_train_async_status_delete
[  FAILED  ] caffeapi.service_train_async_final_status
[  FAILED  ] caffeapi.service_train_async_and_predict
[  FAILED  ] caffeapi.service_predict
[  FAILED  ] caffeapi.service_train_csv
[  FAILED  ] caffeapi.service_train_csv_in_memory
[  FAILED  ] caffeapi.service_train_images
[  FAILED  ] caffeapi.service_train_txt
[  FAILED  ] caffeapi.service_train_txt_char
[  FAILED  ] caffeapi.service_train_csv_mt_regression

11 FAILED TESTS
```

No idea of how to even get started, any hints would be appreciated.

**Comment by beniz** [comment] 2016-03-06 21:17
OK thanks. This is gonna take some time as your build will need to be replicated.

**Comment by Isaacpm** [comment] 2016-03-06 21:36
I have it in a virtual box VM, I can export it and share it.
It will take less than installing the OS from scratch and compile everything

**Comment by beniz** [comment] 2016-03-06 22:10
I was contemplating the use of docker for this. What do you think ?

**Comment by Isaacpm** [comment] 2016-03-06 22:34
Not 100% sure, from my understanding of docker. 
Why would you want a centos docker image vs and ubuntu docker image, if what you have is a running dede instance. Which is really independent on the OS, you can run it in any host, get the image updated from docker itself every time there is a new version. 
Unless you want it to test the installation in CentOS, to then provide an installation procedure to install it natively.
I could build a centos docker image with the same state I've got my installation now and upload it to my deepdetect public repo if you want.
I'm just more comfortable still with full OS VMs than docker images, that's why I was using it for testing.

**Comment by beniz** [comment] 2016-03-07 18:03
@Isaacpm I've been able to test your installation steps on a docker CentOS image. Thanks for the great work, I know how long these steps and compilation hurdles can take.

Interestingly the unit tests are perfectly fine on my build.

The only step I am not really happy with and that was highlighted as such is:
```
cp -rva /usr/local/include/boost/* /usr/include/
cp /usr/include/openblas/* /usr/include/
cp -rva /cpp-netlib-0.11.2-final/boost/ /usr/include
```

The solution is to pass the `/usr/include/openblas` and other repositories to the `CAFFE_INC_DIR` variable. The currrent code in `deepdetect/CMakeLists.txt` doesn't really allows this because specifying `CAFFE_INC_DIR` directly skips the Caffe compilation. This is because as of now, this is the way provided to test `deepdetect` against a new version of Caffe without modifying anything.

**Comment by Isaacpm** [comment] 2016-03-07 20:03
@beniz, that's cool.
If it works for you it's enough, i'll be using the docker containers or the ubuntu installations, so no need for this craziness.
I did try all sorts of includes during compilation time and none worked, that's why I settled for the ugly copy all solution.
But if you say it's the only one for now, well, it's enough.

Glad to have been of some help :-)

**Comment by akshaypai** [comment] 2016-07-07 06:36
I am getting this error even though I am running a docker container on  Cent OS. It shouldn't matter whats the base OS is right ? if I use an Ubuntu Docker image, im guessing  that it should have been fine. 

What can I do to make this work ?

**Comment by beniz** [comment] 2016-07-07 08:10
@akshaypai the highlighted steps from https://github.com/beniz/deepdetect/issues/71#issuecomment-193372956 should basically work if you wish to compile natively. I'm not sure what error you are referring to, giving more targeted elements (all calls, server log etc...) helps us provide a more targeted and effective answer.

**Comment by beniz** [comment] 2018-10-16 19:57
Final answer at this stage would be to use docker images, see https://github.com/jolibrain/deepdetect/tree/master/docker

**Closed by beniz** 2018-10-16 19:57 UTC
Labels: compilation, packaging
